port: 9080
database:
  host: "localhost"
  port: 6432
  user: "postgresUser"
  password: "postgresPW"
  dbname: "postgresDB"

jwt:
  pubKeyFile: "./zertifikat-pub.pem"

mqtt:
  host: "tcp://localhost:1883"
  id: "edash-backend-1"
  qos: 0

file-content:
  basedir: "../../file-content/"
  templates: "./public"

services:
  mail-server: "localhost:9090"