#!/bin/sh
set -e

if [ -n "$VFEEG_BACKEND_DATABASE_PASSWORD_FILE" ] && [ -r "$VFEEG_BACKEND_DATABASE_PASSWORD_FILE" ]; then
  export VFEEG_BACKEND_DATABASE_PASSWORD="$(cat "$VFEEG_BACKEND_DATABASE_PASSWORD_FILE")"
fi

exec "$@"