package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"at.ourproject/vfeeg-backend/api/middleware"
	"at.ourproject/vfeeg-backend/database"
	"at.ourproject/vfeeg-backend/graph/generated"
	"at.ourproject/vfeeg-backend/graph/gmodel"
	"at.ourproject/vfeeg-backend/model"
	"github.com/99designs/gqlgen/graphql"
)

// UpdateEegModel is the resolver for the updateEegModel field.
func (r *mutationResolver) UpdateEegModel(ctx context.Context, tenant string, eegModel *gmodel.EegModel) (*model.Eeg, error) {
	db, err := database.GetDB(context.Background())
	if err != nil {
		return nil, err
	}

	eeg, err := db.GetEegById(tenant)
	if err != nil {
		return nil, err
	}

	if eegModel.SettlementInterval != nil {
		eeg.SettlementInterval = *eegModel.SettlementInterval
	}
	if eegModel.SepaActiv != nil {
		eeg.AccountInfo.Sepa = *eegModel.SepaActiv
	}

	return eeg, nil
}

// MasterDataUpload is the resolver for the masterDataUpload field.
func (r *mutationResolver) MasterDataUpload(ctx context.Context, tenant string, sheet string, file graphql.Upload) (bool, error) {
	db, err := database.GetDB(ctx)
	if err != nil {
		return false, err
	}

	if err = db.ImportMasterdataFromExcel(file.File, file.Filename, sheet, tenant); err != nil {
		return false, err
	}
	return true, nil
}

// Eeg is the resolver for the eeg field.
func (r *queryResolver) Eeg(ctx context.Context) (*model.Eeg, error) {
	tenant := middleware.ForContextTenant(ctx)

	db, err := database.GetDB(context.Background())
	if err != nil {
		return nil, err
	}

	eeg, err := db.GetEegById(tenant)
	if err != nil {
		return nil, err
	}
	return eeg, nil
}

// Links is the resolver for the links field.
func (r *queryResolver) Links(ctx context.Context) ([]*gmodel.Link, error) {
	panic(fmt.Errorf("not implemented: Links - links"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
