// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gmodel

type EegModel struct {
	Tenant             *string `json:"tenant" mapstructure:",omitempty"`
	SettlementInterval *string `json:"settlementInterval" mapstructure:",omitempty"`
	SepaActiv          *bool   `json:"sepaActiv" mapstructure:",omitempty"`
}

type Link struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Address string `json:"address"`
}
