// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/mail.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMailWithInlineAttachmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	HtmlBody      string                 `protobuf:"bytes,4,opt,name=htmlBody,proto3" json:"htmlBody,omitempty"`
	InlineContent []*Attachment          `protobuf:"bytes,5,rep,name=inlineContent,proto3" json:"inlineContent,omitempty"`
	Cc            *string                `protobuf:"bytes,6,opt,name=cc,proto3,oneof" json:"cc,omitempty"`
	Attachment    *Attachment            `protobuf:"bytes,7,opt,name=attachment,proto3,oneof" json:"attachment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailWithInlineAttachmentsRequest) Reset() {
	*x = SendMailWithInlineAttachmentsRequest{}
	mi := &file_proto_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailWithInlineAttachmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailWithInlineAttachmentsRequest) ProtoMessage() {}

func (x *SendMailWithInlineAttachmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailWithInlineAttachmentsRequest.ProtoReflect.Descriptor instead.
func (*SendMailWithInlineAttachmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{0}
}

func (x *SendMailWithInlineAttachmentsRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendMailWithInlineAttachmentsRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *SendMailWithInlineAttachmentsRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendMailWithInlineAttachmentsRequest) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *SendMailWithInlineAttachmentsRequest) GetInlineContent() []*Attachment {
	if x != nil {
		return x.InlineContent
	}
	return nil
}

func (x *SendMailWithInlineAttachmentsRequest) GetCc() string {
	if x != nil && x.Cc != nil {
		return *x.Cc
	}
	return ""
}

func (x *SendMailWithInlineAttachmentsRequest) GetAttachment() *Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

type SendMailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Cc            *string                `protobuf:"bytes,4,opt,name=cc,proto3,oneof" json:"cc,omitempty"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3,oneof" json:"body,omitempty"`
	Attachment    *Attachment            `protobuf:"bytes,6,opt,name=attachment,proto3,oneof" json:"attachment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailRequest) Reset() {
	*x = SendMailRequest{}
	mi := &file_proto_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailRequest) ProtoMessage() {}

func (x *SendMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailRequest.ProtoReflect.Descriptor instead.
func (*SendMailRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{1}
}

func (x *SendMailRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendMailRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *SendMailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendMailRequest) GetCc() string {
	if x != nil && x.Cc != nil {
		return *x.Cc
	}
	return ""
}

func (x *SendMailRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SendMailRequest) GetAttachment() *Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

// The response status for sending emails
type SendMailReply struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Status  int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// Recipients the mail server refused (invalid address) and did not
	// deliver to. Empty on full delivery. Additive field — old clients
	// and servers simply ignore it.
	RejectedRecipients []string `protobuf:"bytes,3,rep,name=rejectedRecipients,proto3" json:"rejectedRecipients,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SendMailReply) Reset() {
	*x = SendMailReply{}
	mi := &file_proto_mail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailReply) ProtoMessage() {}

func (x *SendMailReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailReply.ProtoReflect.Descriptor instead.
func (*SendMailReply) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{2}
}

func (x *SendMailReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SendMailReply) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *SendMailReply) GetRejectedRecipients() []string {
	if x != nil {
		return x.RejectedRecipients
	}
	return nil
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	ContentId     *string                `protobuf:"bytes,4,opt,name=contentId,proto3,oneof" json:"contentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_proto_mail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{3}
}

func (x *Attachment) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Attachment) GetContentId() string {
	if x != nil && x.ContentId != nil {
		return *x.ContentId
	}
	return ""
}

var File_proto_mail_proto protoreflect.FileDescriptor

const file_proto_mail_proto_rawDesc = "" +
	"\n" +
	"\x10proto/mail.proto\x12\rat.energydash\"\xbe\x02\n" +
	"$SendMailWithInlineAttachmentsRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x1a\n" +
	"\bhtmlBody\x18\x04 \x01(\tR\bhtmlBody\x12?\n" +
	"\rinlineContent\x18\x05 \x03(\v2\x19.at.energydash.AttachmentR\rinlineContent\x12\x13\n" +
	"\x02cc\x18\x06 \x01(\tH\x00R\x02cc\x88\x01\x01\x12>\n" +
	"\n" +
	"attachment\x18\a \x01(\v2\x19.at.energydash.AttachmentH\x01R\n" +
	"attachment\x88\x01\x01B\x05\n" +
	"\x03_ccB\r\n" +
	"\v_attachment\"\xee\x01\n" +
	"\x0fSendMailRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x13\n" +
	"\x02cc\x18\x04 \x01(\tH\x00R\x02cc\x88\x01\x01\x12\x17\n" +
	"\x04body\x18\x05 \x01(\fH\x01R\x04body\x88\x01\x01\x12>\n" +
	"\n" +
	"attachment\x18\x06 \x01(\v2\x19.at.energydash.AttachmentH\x02R\n" +
	"attachment\x88\x01\x01B\x05\n" +
	"\x03_ccB\a\n" +
	"\x05_bodyB\r\n" +
	"\v_attachment\"\x82\x01\n" +
	"\rSendMailReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01\x12.\n" +
	"\x12rejectedRecipients\x18\x03 \x03(\tR\x12rejectedRecipientsB\n" +
	"\n" +
	"\b_message\"\x8f\x01\n" +
	"\n" +
	"Attachment\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1a\n" +
	"\bmimeType\x18\x03 \x01(\tR\bmimeType\x12!\n" +
	"\tcontentId\x18\x04 \x01(\tH\x00R\tcontentId\x88\x01\x01B\f\n" +
	"\n" +
	"_contentId2\xd2\x01\n" +
	"\x0fSendMailService\x12s\n" +
	"\x1cSendMailWithInlineAttachment\x123.at.energydash.SendMailWithInlineAttachmentsRequest\x1a\x1c.at.energydash.SendMailReply\"\x00\x12J\n" +
	"\bSendMail\x12\x1e.at.energydash.SendMailRequest\x1a\x1c.at.energydash.SendMailReply\"\x00BO\n" +
	"\x18at.energydash.admin.mailB\x0eMailAdminProtoP\x01Z!at.ourproject/vfeeg-backend/protob\x06proto3"

var (
	file_proto_mail_proto_rawDescOnce sync.Once
	file_proto_mail_proto_rawDescData []byte
)

func file_proto_mail_proto_rawDescGZIP() []byte {
	file_proto_mail_proto_rawDescOnce.Do(func() {
		file_proto_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mail_proto_rawDesc), len(file_proto_mail_proto_rawDesc)))
	})
	return file_proto_mail_proto_rawDescData
}

var file_proto_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_mail_proto_goTypes = []any{
	(*SendMailWithInlineAttachmentsRequest)(nil), // 0: at.energydash.SendMailWithInlineAttachmentsRequest
	(*SendMailRequest)(nil),                      // 1: at.energydash.SendMailRequest
	(*SendMailReply)(nil),                        // 2: at.energydash.SendMailReply
	(*Attachment)(nil),                           // 3: at.energydash.Attachment
}
var file_proto_mail_proto_depIdxs = []int32{
	3, // 0: at.energydash.SendMailWithInlineAttachmentsRequest.inlineContent:type_name -> at.energydash.Attachment
	3, // 1: at.energydash.SendMailWithInlineAttachmentsRequest.attachment:type_name -> at.energydash.Attachment
	3, // 2: at.energydash.SendMailRequest.attachment:type_name -> at.energydash.Attachment
	0, // 3: at.energydash.SendMailService.SendMailWithInlineAttachment:input_type -> at.energydash.SendMailWithInlineAttachmentsRequest
	1, // 4: at.energydash.SendMailService.SendMail:input_type -> at.energydash.SendMailRequest
	2, // 5: at.energydash.SendMailService.SendMailWithInlineAttachment:output_type -> at.energydash.SendMailReply
	2, // 6: at.energydash.SendMailService.SendMail:output_type -> at.energydash.SendMailReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_mail_proto_init() }
func file_proto_mail_proto_init() {
	if File_proto_mail_proto != nil {
		return
	}
	file_proto_mail_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_mail_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_mail_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_mail_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mail_proto_rawDesc), len(file_proto_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mail_proto_goTypes,
		DependencyIndexes: file_proto_mail_proto_depIdxs,
		MessageInfos:      file_proto_mail_proto_msgTypes,
	}.Build()
	File_proto_mail_proto = out.File
	file_proto_mail_proto_goTypes = nil
	file_proto_mail_proto_depIdxs = nil
}
