// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: proto/mail.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SendMailService_SendMailWithInlineAttachment_FullMethodName = "/at.energydash.SendMailService/SendMailWithInlineAttachment"
	SendMailService_SendMail_FullMethodName                     = "/at.energydash.SendMailService/SendMail"
)

// SendMailServiceClient is the client API for SendMailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendMailServiceClient interface {
	// Sends a greeting
	SendMailWithInlineAttachment(ctx context.Context, in *SendMailWithInlineAttachmentsRequest, opts ...grpc.CallOption) (*SendMailReply, error)
	SendMail(ctx context.Context, in *SendMailRequest, opts ...grpc.CallOption) (*SendMailReply, error)
}

type sendMailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSendMailServiceClient(cc grpc.ClientConnInterface) SendMailServiceClient {
	return &sendMailServiceClient{cc}
}

func (c *sendMailServiceClient) SendMailWithInlineAttachment(ctx context.Context, in *SendMailWithInlineAttachmentsRequest, opts ...grpc.CallOption) (*SendMailReply, error) {
	out := new(SendMailReply)
	err := c.cc.Invoke(ctx, SendMailService_SendMailWithInlineAttachment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendMailServiceClient) SendMail(ctx context.Context, in *SendMailRequest, opts ...grpc.CallOption) (*SendMailReply, error) {
	out := new(SendMailReply)
	err := c.cc.Invoke(ctx, SendMailService_SendMail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendMailServiceServer is the server API for SendMailService service.
// All implementations must embed UnimplementedSendMailServiceServer
// for forward compatibility
type SendMailServiceServer interface {
	// Sends a greeting
	SendMailWithInlineAttachment(context.Context, *SendMailWithInlineAttachmentsRequest) (*SendMailReply, error)
	SendMail(context.Context, *SendMailRequest) (*SendMailReply, error)
	mustEmbedUnimplementedSendMailServiceServer()
}

// UnimplementedSendMailServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSendMailServiceServer struct {
}

func (UnimplementedSendMailServiceServer) SendMailWithInlineAttachment(context.Context, *SendMailWithInlineAttachmentsRequest) (*SendMailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMailWithInlineAttachment not implemented")
}
func (UnimplementedSendMailServiceServer) SendMail(context.Context, *SendMailRequest) (*SendMailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMail not implemented")
}
func (UnimplementedSendMailServiceServer) mustEmbedUnimplementedSendMailServiceServer() {}

// UnsafeSendMailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendMailServiceServer will
// result in compilation errors.
type UnsafeSendMailServiceServer interface {
	mustEmbedUnimplementedSendMailServiceServer()
}

func RegisterSendMailServiceServer(s grpc.ServiceRegistrar, srv SendMailServiceServer) {
	s.RegisterService(&SendMailService_ServiceDesc, srv)
}

func _SendMailService_SendMailWithInlineAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMailWithInlineAttachmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendMailServiceServer).SendMailWithInlineAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SendMailService_SendMailWithInlineAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendMailServiceServer).SendMailWithInlineAttachment(ctx, req.(*SendMailWithInlineAttachmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SendMailService_SendMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendMailServiceServer).SendMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SendMailService_SendMail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendMailServiceServer).SendMail(ctx, req.(*SendMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SendMailService_ServiceDesc is the grpc.ServiceDesc for SendMailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendMailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "at.energydash.SendMailService",
	HandlerType: (*SendMailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMailWithInlineAttachment",
			Handler:    _SendMailService_SendMailWithInlineAttachment_Handler,
		},
		{
			MethodName: "SendMail",
			Handler:    _SendMailService_SendMail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mail.proto",
}
